//! On-chain identifiers for the equivocation-slashing predeploy (#732b).
//!
//! The `Slashing` contract (`contracts/Slashing.sol`), deployed as a genesis
//! predeploy at [`SLASHING_ADDRESS`], verifies a validator equivocation proof
//! **in the EVM** and, on success, emits [`Slashed`](SLASHED_TOPIC). A watcher
//! submits two `Vote`s for the same view but different blocks; the predeploy
//! reads the validator's BLS key from the registry (#732a `keyAt`), reconstructs
//! both `preimage::<Vote>` signing messages, and verifies both signatures via
//! the Prague EIP-2537 precompiles (see `contracts/BlsVerify.sol`).
//!
//! It only **verifies + signals** — the economic penalty stays
//! consensus-authoritative (#654): boule reads `Slashed` from each committed
//! block (the #655/#730 `eth_getLogs` pattern, the next #732 step) and applies
//! it through its `StakeSource` → jail (the #658 apply-target). So this module,
//! like the staking/rotation ones, declares the on-chain identifiers (mirrored
//! as constants and pinned to the genesis bytecode by the tests below).
//!
//! The full verify + emit path is exercised against a live reth (see the PR /
//! `contracts/test/slashing.mjs`): a valid equivocation emits `Slashed`, while a
//! same-block proof or a signature that does not match its block reverts.

/// Fixed genesis-predeploy address of the slashing contract (one past the
/// registry predeploy at `…b12`).
pub const SLASHING_ADDRESS: &str = "0x0000000000000000000000000000000000000b13";

/// `keccak256("Slashed(bytes32,uint64,bytes32,bytes32)")` — topic0 of the
/// `Slashed` event boule's read path (next #732 step) filters on.
pub const SLASHED_TOPIC: &str =
    "0xaa027002e2293d2bdf5dfdb36085da833212945f22a1bc33658aab00be192988";

/// 4-byte selector of
/// `submitEquivocation(bytes32,bytes,uint64,bytes32,bytes,bytes32,bytes)` — the
/// proof-submission entrypoint a watcher calls.
pub const SUBMIT_EQUIVOCATION_SELECTOR: [u8; 4] = [0xa3, 0x9f, 0xe9, 0xc0];

#[cfg(test)]
mod tests {
    use super::*;

    /// The slashing predeploy must be seeded in `genesis.json` at
    /// [`SLASHING_ADDRESS`] with non-empty code, or watchers would submit proofs
    /// to a dead address. Pins the Rust constant to the (generated) on-chain
    /// artifact.
    #[test]
    fn slashing_predeploy_present_in_genesis_at_address() {
        let g: serde_json::Value =
            serde_json::from_str(include_str!("../genesis.json")).expect("genesis.json parses");
        let code = g["alloc"][SLASHING_ADDRESS]["code"]
            .as_str()
            .expect("a predeploy with code is seeded at SLASHING_ADDRESS");
        assert!(code.starts_with("0x60"), "looks like EVM runtime bytecode");
        assert!(code.len() > 2 + 1000 * 2, "non-trivial contract code");
    }

    /// The event topic and function selector the Rust constants declare must be
    /// the ones solc compiled into the predeploy bytecode. Ties the constants to
    /// the artifact without a keccak dependency: if the ABI changes, the
    /// generated bytecode changes and this fails.
    #[test]
    fn topic_and_selector_match_genesis_bytecode() {
        let g: serde_json::Value =
            serde_json::from_str(include_str!("../genesis.json")).expect("genesis.json parses");
        let code = g["alloc"][SLASHING_ADDRESS]["code"].as_str().unwrap();
        assert!(
            code.contains(SLASHED_TOPIC.trim_start_matches("0x")),
            "Slashed event topic must appear as the LOG topic operand",
        );
        assert!(
            code.contains(&hex::encode(SUBMIT_EQUIVOCATION_SELECTOR)),
            "submitEquivocation selector must appear in the dispatcher",
        );
    }
}
