#!/usr/bin/env bash
# Render docker-compose + systemd run tooling for a generated boule testnet.
# Invoked by gen-testnet.sh; reads the artifact layout it produced.
#
#   render-run-tooling.sh <OUTDIR> <N> <M> <HOST>
#
# Emits:
#   <OUTDIR>/docker-compose.yml      — one reth + one boule service per slot
#   <OUTDIR>/systemd/*.service       — systemd unit templates per slot
#   <OUTDIR>/run-local.sh            — bare-process bring-up (no docker)
#
# The compose topology mirrors cluster-el-e2e.sh: N validators + M full nodes,
# each driving its own reth EL over the Engine API, all on one bridge network.
set -uo pipefail

OUTDIR="$1"; N="$2"; M="$3"; HOST="$4"
SLOTS=$((N + M))

authport() { echo $((8551 + 10 * $1)); }
httpport() { echo $((8545 + 10 * $1)); }
elp2p()    { echo $((30330 + $1)); }
p2pport()  { echo $((7001 + $1)); }
apiport()  { echo $((8001 + $1)); }
adminport(){ echo $((9001 + $1)); }
role_of()  { [ "$1" -lt "$N" ] && echo validator || echo full; }

# Images are operator-supplied: build boule (--features reth) and boule-reth-node
# into containers, or bind-mount the host binaries. We reference them by name and
# document the build in the runbook; the compose file bind-mounts the artifact dir.
BOULE_IMAGE="${BOULE_IMAGE:-boule:latest}"
RETH_IMAGE="${RETH_IMAGE:-boule-reth-node:latest}"

# ── docker-compose.yml ──
COMPOSE="$OUTDIR/docker-compose.yml"
{
  echo "# Generated by gen-testnet.sh — $N validators + $M full nodes, each with its own reth EL."
  echo "# Bring up:   docker compose -f docker-compose.yml up -d"
  echo "# Images:     build boule (--features reth) as \$BOULE_IMAGE and boule-reth-node as \$RETH_IMAGE,"
  echo "#             or bind-mount host binaries into /usr/local/bin (see docs/join-testnet.md)."
  echo "services:"
  for i in $(seq 0 $((SLOTS - 1))); do
    role=$(role_of "$i")
    echo "  reth-$i:"
    echo "    image: \${RETH_IMAGE:-$RETH_IMAGE}"
    echo "    container_name: boule-reth-$i"
    echo "    command: >"
    echo "      node --chain /genesis/genesis.json --datadir /data/reth$i"
    echo "      --authrpc.addr 0.0.0.0 --authrpc.port $(authport "$i") --authrpc.jwtsecret /data/jwt$i.hex"
    echo "      --http --http.addr 0.0.0.0 --http.port $(httpport "$i")"
    echo "      --http.api eth,net,web3,txpool,admin"
    echo "      --port $(elp2p "$i") --ipcdisable"
    echo "    volumes:"
    echo "      - ./genesis:/genesis:ro"
    echo "      - ./data:/data"
    echo "    ports:"
    echo "      - \"$(httpport "$i"):$(httpport "$i")\"   # eth JSON-RPC"
    echo "    networks: [testnet]"
    echo "  boule-$i:"
    echo "    image: \${BOULE_IMAGE:-$BOULE_IMAGE}"
    echo "    container_name: boule-$i-$role"
    echo "    depends_on: [reth-$i]"
    echo "    command: start --config /configs/node$i.toml"
    echo "    volumes:"
    echo "      - ./configs:/configs:ro"
    echo "      - ./keys:/keys:ro"
    echo "      - ./genesis:/genesis:ro"
    echo "      - ./data:/data"
    echo "    ports:"
    echo "      - \"$(apiport "$i"):$(apiport "$i")\"     # boule public API"
    echo "    networks: [testnet]"
  done
  echo "networks:"
  echo "  testnet:"
  echo "    driver: bridge"
} > "$COMPOSE"
echo "   wrote $COMPOSE"

# ── systemd unit templates ──
mkdir -p "$OUTDIR/systemd"
for i in $(seq 0 $((SLOTS - 1))); do
  role=$(role_of "$i")
  cat > "$OUTDIR/systemd/boule-reth-$i.service" <<EOF
[Unit]
Description=boule reth EL (slot $i, $role)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/boule-reth-node node --chain ${OUTDIR}/genesis/genesis.json \\
  --datadir ${OUTDIR}/data/reth$i \\
  --authrpc.addr 127.0.0.1 --authrpc.port $(authport "$i") --authrpc.jwtsecret ${OUTDIR}/data/jwt$i.hex \\
  --http --http.addr 127.0.0.1 --http.port $(httpport "$i") --http.api eth,net,web3,txpool,admin \\
  --port $(elp2p "$i") --ipcdisable
Restart=on-failure
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF
  cat > "$OUTDIR/systemd/boule-$i.service" <<EOF
[Unit]
Description=boule consensus node (slot $i, $role)
After=boule-reth-$i.service network-online.target
Wants=boule-reth-$i.service

[Service]
Type=simple
ExecStart=/usr/local/bin/boule start --config ${OUTDIR}/configs/node$i.toml
Restart=on-failure
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF
done
echo "   wrote $OUTDIR/systemd/*.service ($SLOTS slots)"

# ── bare-process local bring-up (no docker) ──
RUN="$OUTDIR/run-local.sh"
{
  echo "#!/usr/bin/env bash"
  echo "# Bare-process bring-up of the generated testnet (no docker). Needs"
  echo "# boule (--features reth) + boule-reth-node on PATH or via \$BOULE / \$EL_BIN."
  echo "# Tears every process down on exit. For a self-contained local smoke test."
  echo "set -uo pipefail"
  echo "OUTDIR=\"\$(cd \"\$(dirname \"\$0\")\" && pwd)\""
  echo "BOULE=\"\${BOULE:-boule}\"; EL_BIN=\"\${EL_BIN:-boule-reth-node}\""
  echo "PIDS=()"
  echo "cleanup(){ for p in \"\${PIDS[@]}\"; do kill \"\$p\" 2>/dev/null || true; done; }"
  echo "trap cleanup EXIT INT TERM"
  echo "mkdir -p \"\$OUTDIR/data\""
  echo "HTTP=($(for i in $(seq 0 $((SLOTS - 1))); do printf '%s ' "$(httpport "$i")"; done))"
  echo "ELP2P=($(for i in $(seq 0 $((SLOTS - 1))); do printf '%s ' "$(elp2p "$i")"; done))"
  for i in $(seq 0 $((SLOTS - 1))); do
    echo "\"\$EL_BIN\" node --chain \"\$OUTDIR/genesis/genesis.json\" --datadir \"\$OUTDIR/data/reth$i\" \\"
    echo "  --authrpc.addr 127.0.0.1 --authrpc.port $(authport "$i") --authrpc.jwtsecret \"\$OUTDIR/data/jwt$i.hex\" \\"
    echo "  --http --http.addr 127.0.0.1 --http.port $(httpport "$i") --http.api eth,net,web3,txpool,admin \\"
    echo "  --disable-discovery --ipcdisable --port $(elp2p "$i") > \"\$OUTDIR/data/el$i.log\" 2>&1 & PIDS+=(\$!)"
  done
  # Wait for every EL's RPC, then admin_addPeer-mesh the reths so a rotated
  # leader's built payload reaches every node's EL (matches cluster-el-e2e.sh).
  cat <<'MESH'
for p in "${HTTP[@]}"; do
  for _ in $(seq 1 60); do
    curl -fsS -X POST "http://127.0.0.1:$p" -H 'content-type: application/json' \
      -d '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}' >/dev/null 2>&1 && break
    sleep 1
  done
done
enode_of(){ curl -fsS -X POST "http://127.0.0.1:$1" -H 'content-type: application/json' \
  -d '{"jsonrpc":"2.0","id":1,"method":"admin_nodeInfo","params":[]}' \
  | jq -r '.result.enode' | sed -E "s/@127.0.0.1:[0-9]+/@127.0.0.1:$2/; s/\\?.*$//"; }
declare -a ENODES
for k in "${!HTTP[@]}"; do ENODES[$k]=$(enode_of "${HTTP[$k]}" "${ELP2P[$k]}"); done
for k in "${!HTTP[@]}"; do for j in "${!HTTP[@]}"; do [ "$k" = "$j" ] && continue
  curl -fsS -X POST "http://127.0.0.1:${HTTP[$k]}" -H 'content-type: application/json' \
    -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"admin_addPeer\",\"params\":[\"${ENODES[$j]}\"]}" >/dev/null 2>&1 || true
done; done
echo "reth mesh wired (${#HTTP[@]} ELs)"
MESH
  for i in $(seq 0 $((SLOTS - 1))); do
    echo "\"\$BOULE\" start --config \"\$OUTDIR/configs/node$i.toml\" > \"\$OUTDIR/data/boule$i.log\" 2>&1 & PIDS+=(\$!)"
  done
  echo "echo 'testnet up: $N validators + $M full nodes. Ctrl-C to tear down.'"
  echo "wait"
} > "$RUN"
chmod +x "$RUN"
echo "   wrote $RUN"
