#!/usr/bin/env bash
# Render docker-compose + systemd run tooling for a generated boule testnet.
# Invoked by gen-testnet.sh; reads the artifact layout it produced.
#
#   render-run-tooling.sh <OUTDIR> <N> <M> <HOST>
#
# Emits:
#   <OUTDIR>/docker-compose.yml      — one reth + one boule service per slot
#   <OUTDIR>/systemd/*.service       — systemd unit templates per slot
#   <OUTDIR>/run-local.sh            — bare-process bring-up (no docker)
#
# The compose topology mirrors cluster-el-e2e.sh: N validators + M full nodes,
# each driving its own reth EL over the Engine API, all on one bridge network.
set -uo pipefail

OUTDIR="$1"; N="$2"; M="$3"; HOST="$4"
SLOTS=$((N + M))

authport()  { echo $((8551 + 10 * $1)); }
httpport()  { echo $((8545 + 10 * $1)); }
proxyport() { echo $((8547 + 10 * $1)); }
elp2p()     { echo $((30330 + $1)); }
p2pport()   { echo $((7001 + $1)); }
apiport()   { echo $((8001 + $1)); }
adminport() { echo $((9001 + $1)); }
role_of()   { [ "$1" -lt "$N" ] && echo validator || echo full; }

# Images are operator-supplied: build boule (--features reth) and boule-reth-node
# into containers, or bind-mount the host binaries. We reference them by name and
# document the build in the runbook; the compose file bind-mounts the artifact dir.
BOULE_IMAGE="${BOULE_IMAGE:-boule:latest}"
RETH_IMAGE="${RETH_IMAGE:-boule-reth-node:latest}"

# ── docker-compose.yml ──
COMPOSE="$OUTDIR/docker-compose.yml"
{
  echo "# Generated by gen-testnet.sh — $N validators + $M full nodes, each with its own reth EL."
  echo "# Bring up:   docker compose -f docker-compose.yml up -d"
  echo "# Images:     build boule (--features reth) as \$BOULE_IMAGE and boule-reth-node as \$RETH_IMAGE,"
  echo "#             or bind-mount host binaries into /usr/local/bin (see docs/join-testnet.md)."
  echo "# SECURITY (#822): reth's HTTP RPC and Engine API are NOT host-published."
  echo "# reth listens only on the internal 'testnet' bridge (no 'ports:' entry), so"
  echo "# admin_*/txpool_*/engine_* are unreachable from the host/internet. The ONLY"
  echo "# public eth ingress is the eth-rpc-proxy, which forwards the allow-listed"
  echo "# read-only + eth_sendRawTransaction surface. --http.api is eth,net,web3 (no"
  echo "# txpool,admin), and the Engine API stays JWT-auth'd + bridge-only."
  echo "services:"
  for i in $(seq 0 $((SLOTS - 1))); do
    role=$(role_of "$i")
    echo "  reth-$i:"
    echo "    image: \${RETH_IMAGE:-$RETH_IMAGE}"
    echo "    container_name: boule-reth-$i"
    echo "    # Wrapped in sh so it picks up an optional /data/reth$i.trusted-peers"
    echo "    # file (#826): reth-mesh.sh scrapes each reth's enode post-boot and"
    echo "    # writes that file, then restarts this service so a wiped/late-join"
    echo "    # follower's reth devp2p-syncs the unretained gap from its peers."
    echo "    entrypoint: [\"/bin/sh\", \"-c\"]"
    echo "    command:"
    echo "      - >"
    echo "        TP=\"\"; [ -s /data/reth$i.trusted-peers ] &&"
    echo "        TP=\"--trusted-peers \$\$(cat /data/reth$i.trusted-peers)\";"
    echo "        exec boule-reth-node node --chain /genesis/genesis.json --datadir /data/reth$i"
    echo "        --authrpc.addr 0.0.0.0 --authrpc.port $(authport "$i") --authrpc.jwtsecret /data/jwt$i.hex"
    echo "        --http --http.addr 0.0.0.0 --http.port $(httpport "$i")"
    echo "        --http.api eth,net,web3"
    echo "        --port $(elp2p "$i") --addr 0.0.0.0 --ipcdisable \$\$TP"
    echo "    volumes:"
    echo "      - ./genesis:/genesis:ro"
    echo "      - ./data:/data"
    echo "    # No HTTP/Engine 'ports:' — RPC ($(httpport "$i")) + Engine API ($(authport "$i")) are reachable"
    echo "    # only on the internal bridge (by eth-rpc-proxy-$i / boule-$i), never the host."
    echo "    # The devp2p port ($(elp2p "$i")) IS open on the bridge so reths peer (#826),"
    echo "    # but is NOT host-published — peering is intra-cluster, not public."
    echo "    expose: [\"$(elp2p "$i")\"]"
    echo "    networks: [testnet]"
    echo "  eth-rpc-proxy-$i:"
    echo "    image: \${BOULE_IMAGE:-$BOULE_IMAGE}"
    echo "    container_name: boule-eth-rpc-proxy-$i"
    echo "    depends_on: [reth-$i]"
    echo "    command: eth-rpc-proxy"
    echo "    environment:"
    echo "      ETH_RPC_PROXY_LISTEN_ADDR: \"0.0.0.0:$(proxyport "$i")\""
    echo "      ETH_RPC_PROXY_BACKEND_URL: \"http://reth-$i:$(httpport "$i")\""
    echo "    ports:"
    echo "      - \"$(proxyport "$i"):$(proxyport "$i")\"   # PUBLIC eth JSON-RPC (allow-listed proxy)"
    echo "    networks: [testnet]"
    echo "  boule-$i:"
    echo "    image: \${BOULE_IMAGE:-$BOULE_IMAGE}"
    echo "    container_name: boule-$i-$role"
    echo "    depends_on: [reth-$i]"
    echo "    command: start --config /configs/node$i.toml"
    echo "    volumes:"
    echo "      - ./configs:/configs:ro"
    echo "      - ./keys:/keys:ro"
    echo "      - ./genesis:/genesis:ro"
    echo "      - ./data:/data"
    echo "    ports:"
    echo "      - \"$(apiport "$i"):$(apiport "$i")\"     # boule public API"
    echo "    networks: [testnet]"
  done
  echo "networks:"
  echo "  testnet:"
  echo "    driver: bridge"
} > "$COMPOSE"
echo "   wrote $COMPOSE"

# ── systemd unit templates ──
mkdir -p "$OUTDIR/systemd"
for i in $(seq 0 $((SLOTS - 1))); do
  role=$(role_of "$i")
  cat > "$OUTDIR/systemd/boule-reth-$i.service" <<EOF
[Unit]
Description=boule reth EL (slot $i, $role)
After=network-online.target
Wants=network-online.target

# SECURITY (#822): HTTP RPC + Engine API bind 127.0.0.1 only. The public eth
# ingress is boule-eth-rpc-proxy-$i.service (allow-listed); --http.api is
# eth,net,web3 (no txpool,admin). Do NOT change --http.addr to 0.0.0.0 or add a
# firewall hole to $(httpport "$i")/$(authport "$i").
[Service]
Type=simple
ExecStart=/usr/local/bin/boule-reth-node node --chain ${OUTDIR}/genesis/genesis.json \\
  --datadir ${OUTDIR}/data/reth$i \\
  --authrpc.addr 127.0.0.1 --authrpc.port $(authport "$i") --authrpc.jwtsecret ${OUTDIR}/data/jwt$i.hex \\
  --http --http.addr 127.0.0.1 --http.port $(httpport "$i") --http.api eth,net,web3 \\
  --port $(elp2p "$i") --ipcdisable
Restart=on-failure
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF
  cat > "$OUTDIR/systemd/boule-eth-rpc-proxy-$i.service" <<EOF
[Unit]
Description=boule public eth-RPC proxy (slot $i, $role)
After=boule-reth-$i.service network-online.target
Wants=boule-reth-$i.service

# The ONLY public eth ingress: forwards the allow-listed read-only +
# eth_sendRawTransaction surface to reth's loopback RPC (#822).
[Service]
Type=simple
Environment=ETH_RPC_PROXY_LISTEN_ADDR=0.0.0.0:$(proxyport "$i")
Environment=ETH_RPC_PROXY_BACKEND_URL=http://127.0.0.1:$(httpport "$i")
ExecStart=/usr/local/bin/eth-rpc-proxy
Restart=on-failure
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF
  cat > "$OUTDIR/systemd/boule-$i.service" <<EOF
[Unit]
Description=boule consensus node (slot $i, $role)
After=boule-reth-$i.service network-online.target
Wants=boule-reth-$i.service

[Service]
Type=simple
ExecStart=/usr/local/bin/boule start --config ${OUTDIR}/configs/node$i.toml
Restart=on-failure
RestartSec=3
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF
done
echo "   wrote $OUTDIR/systemd/*.service ($SLOTS slots)"

# ── reth devp2p peering driver (#826, post-boot two-phase) ──
# Ship the generic peering helper alongside the artifacts, then render a
# topology-pinned driver that scrapes each compose reth's enode from `docker
# logs` and writes a per-node /data/rethN.trusted-peers file, then restarts the
# reth services (which re-exec with --trusted-peers). The reth mesh MIRRORS the
# consensus topology these artifacts build — a trusted-testnet FULL MESH (every
# node peers every other), same as configs' [[peers]]. (For a sentry deployment,
# edit PEERS[] below so a validator's reth peers ONLY its sentries' reths.)
cp "$(cd "$(dirname "$0")" && pwd)/reth-peering.sh" "$OUTDIR/reth-peering.sh"
chmod +x "$OUTDIR/reth-peering.sh"
MESH="$OUTDIR/reth-mesh.sh"
{
  echo "#!/usr/bin/env bash"
  echo "# Wire reth devp2p peering for the compose testnet (#826), post-boot."
  echo "#   bash reth-mesh.sh        # scrape enodes, write trusted-peers, restart reths"
  echo "# Run AFTER 'docker compose up -d' once the reths have logged their enode."
  echo "# Idempotent: re-run after wiping/late-joining a follower's reth to (re)peer it."
  echo "set -uo pipefail"
  echo "OUTDIR=\"\$(cd \"\$(dirname \"\$0\")\" && pwd)\""
  echo "N=$N; M=$M; SLOTS=$SLOTS"
  echo "elp2p() { echo \$((30330 + \$1)); }"
  echo "# docker-compose service/container names per slot."
  echo "svc()  { echo \"reth-\$1\"; }"
  echo "cont() { echo \"boule-reth-\$1\"; }"
  echo "# Scrape slot i's enode from its container log, at its compose-DNS host"
  echo "# (the container name) and devp2p port — the reachable address a PEER dials"
  echo "# (NOT reth's advertised 127.0.0.1)."
  echo "tmp=\$(mktemp -d)"
  echo "specs=()"
  echo "for i in \$(seq 0 \$((SLOTS-1))); do"
  echo "  log=\"\$tmp/reth\$i.log\""
  echo "  docker logs \"\$(cont \"\$i\")\" > \"\$log\" 2>&1 || { echo \"FATAL: no logs for \$(cont \"\$i\") — is it up?\"; exit 1; }"
  echo "  # FULL MESH: peer every OTHER slot. (Sentry: restrict this list.)"
  echo "  peers=\"\"; sep=\"\"; for j in \$(seq 0 \$((SLOTS-1))); do [ \"\$j\" = \"\$i\" ] && continue; peers=\"\$peers\$sep\$j\"; sep=\",\"; done"
  echo "  specs+=(\"name=\$i:log=\$log:host=\$(cont \"\$i\"):port=\$(elp2p \"\$i\"):peers=\$peers\")"
  echo "done"
  echo "bash \"\$OUTDIR/reth-peering.sh\" build \"\$tmp\" \"\${specs[@]}\" || exit 1"
  echo "# Install each node's trusted-peers file where its compose reth reads it,"
  echo "# then restart the reth services so they re-exec with --trusted-peers."
  echo "for i in \$(seq 0 \$((SLOTS-1))); do cp \"\$tmp/\$i.trusted-peers\" \"\$OUTDIR/data/reth\$i.trusted-peers\"; done"
  echo "rm -rf \"\$tmp\""
  echo "echo '── restarting reth services with --trusted-peers ──'"
  echo "docker compose -f \"\$OUTDIR/docker-compose.yml\" restart \$(for i in \$(seq 0 \$((SLOTS-1))); do printf 'reth-%s ' \"\$i\"; done)"
  echo "echo '── reth mesh wired; peers should connect within a few seconds ──'"
} > "$MESH"
chmod +x "$MESH"
echo "   wrote $MESH (+ reth-peering.sh helper)"

# ── bare-process local bring-up (no docker) ──
RUN="$OUTDIR/run-local.sh"
{
  echo "#!/usr/bin/env bash"
  echo "# Bare-process bring-up of the generated testnet (no docker). Needs"
  echo "# boule (--features reth) + boule-reth-node on PATH or via \$BOULE / \$EL_BIN."
  echo "# Tears every process down on exit. For a self-contained local smoke test."
  echo "# SECURITY (#822): everything here binds 127.0.0.1 and publishes NOTHING —"
  echo "# this is a single-host loopback smoke test, not a public deployment. The"
  echo "# public eth ingress is the per-node eth-rpc-proxy (allow-listed, on"
  echo "# 127.0.0.1:\$PROXY here). reth's HTTP is loopback-only and drops 'txpool';"
  echo "# 'admin' is kept ONLY so this script can admin_addPeer-mesh the ELs and is"
  echo "# unreachable off-host. The public docker-compose / systemd tooling does NOT"
  echo "# enable admin at all and never publishes reth's port."
  echo "set -uo pipefail"
  echo "OUTDIR=\"\$(cd \"\$(dirname \"\$0\")\" && pwd)\""
  echo "BOULE=\"\${BOULE:-boule}\"; EL_BIN=\"\${EL_BIN:-boule-reth-node}\""
  echo "PROXY_BIN=\"\${PROXY_BIN:-eth-rpc-proxy}\""
  echo "PIDS=()"
  echo "cleanup(){ for p in \"\${PIDS[@]}\"; do kill \"\$p\" 2>/dev/null || true; done; }"
  echo "trap cleanup EXIT INT TERM"
  echo "mkdir -p \"\$OUTDIR/data\""
  echo "HTTP=($(for i in $(seq 0 $((SLOTS - 1))); do printf '%s ' "$(httpport "$i")"; done))"
  echo "PROXY=($(for i in $(seq 0 $((SLOTS - 1))); do printf '%s ' "$(proxyport "$i")"; done))"
  echo "ELP2P=($(for i in $(seq 0 $((SLOTS - 1))); do printf '%s ' "$(elp2p "$i")"; done))"
  for i in $(seq 0 $((SLOTS - 1))); do
    echo "\"\$EL_BIN\" node --chain \"\$OUTDIR/genesis/genesis.json\" --datadir \"\$OUTDIR/data/reth$i\" \\"
    echo "  --authrpc.addr 127.0.0.1 --authrpc.port $(authport "$i") --authrpc.jwtsecret \"\$OUTDIR/data/jwt$i.hex\" \\"
    echo "  --http --http.addr 127.0.0.1 --http.port $(httpport "$i") --http.api eth,net,web3,admin \\"
    echo "  --disable-discovery --ipcdisable --port $(elp2p "$i") > \"\$OUTDIR/data/el$i.log\" 2>&1 & PIDS+=(\$!)"
  done
  # Wait for every EL's RPC, then admin_addPeer-mesh the reths so a rotated
  # leader's built payload reaches every node's EL (matches cluster-el-e2e.sh).
  cat <<'MESH'
for p in "${HTTP[@]}"; do
  for _ in $(seq 1 60); do
    curl -fsS -X POST "http://127.0.0.1:$p" -H 'content-type: application/json' \
      -d '{"jsonrpc":"2.0","id":1,"method":"eth_blockNumber","params":[]}' >/dev/null 2>&1 && break
    sleep 1
  done
done
enode_of(){ curl -fsS -X POST "http://127.0.0.1:$1" -H 'content-type: application/json' \
  -d '{"jsonrpc":"2.0","id":1,"method":"admin_nodeInfo","params":[]}' \
  | jq -r '.result.enode' | sed -E "s/@127.0.0.1:[0-9]+/@127.0.0.1:$2/; s/\\?.*$//"; }
declare -a ENODES
for k in "${!HTTP[@]}"; do ENODES[$k]=$(enode_of "${HTTP[$k]}" "${ELP2P[$k]}"); done
for k in "${!HTTP[@]}"; do for j in "${!HTTP[@]}"; do [ "$k" = "$j" ] && continue
  curl -fsS -X POST "http://127.0.0.1:${HTTP[$k]}" -H 'content-type: application/json' \
    -d "{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"admin_addPeer\",\"params\":[\"${ENODES[$j]}\"]}" >/dev/null 2>&1 || true
done; done
echo "reth mesh wired (${#HTTP[@]} ELs)"
MESH
  # Public eth ingress: one allow-listed proxy per node, in front of reth's
  # loopback RPC (matches docker-compose / systemd). The proxy — not reth's
  # :$(httpport 0)+ — is what a client/LB talks to (#822).
  for i in $(seq 0 $((SLOTS - 1))); do
    echo "ETH_RPC_PROXY_LISTEN_ADDR=\"127.0.0.1:$(proxyport "$i")\" \\"
    echo "ETH_RPC_PROXY_BACKEND_URL=\"http://127.0.0.1:$(httpport "$i")\" \\"
    echo "  \"\$PROXY_BIN\" > \"\$OUTDIR/data/proxy$i.log\" 2>&1 & PIDS+=(\$!)"
  done
  echo "echo 'eth-rpc-proxy up on 127.0.0.1:{$(for i in $(seq 0 $((SLOTS - 1))); do printf '%s,' "$(proxyport "$i")"; done | sed 's/,$//')}'"
  for i in $(seq 0 $((SLOTS - 1))); do
    echo "\"\$BOULE\" start --config \"\$OUTDIR/configs/node$i.toml\" > \"\$OUTDIR/data/boule$i.log\" 2>&1 & PIDS+=(\$!)"
  done
  echo "echo 'testnet up: $N validators + $M full nodes. Ctrl-C to tear down.'"
  echo "wait"
} > "$RUN"
chmod +x "$RUN"
echo "   wrote $RUN"
